# Generated by Django 2.2 on 2019-05-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=5000)),
                ('sign_off', models.CharField(max_length=50)),
            ],
        ),
    ]
