# Generated by Django 2.2 on 2019-05-02 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pings', '0002_ping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ping',
            old_name='sign_off',
            new_name='employee_name',
        ),
    ]
