# Generated by Django 2.2 on 2019-05-02 01:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pings', '0004_auto_20190502_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='ping',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
    ]
